### ISSUE TITLE
toolbox command fails

### ISSUE THREAD

**Issue by heckchuckman** [react-toolbox/react-toolbox-themr#10]
Hi, I'm getting the following error when I run "npm run toolbox" ...

```
> react-toolbox-themr

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at processComponent (/Users/heck/Documents/Sandbox/boilerplate/client/node_modules/react-toolbox-themr/bin/builder.js:44:30)
```

I'm using CRA as a base. Here is the toolbox bit from package.json.
```

"reactToolbox": {
        "include": [
            "APPBAR",
            "AVATAR",
            "BUTTON",
            "CARD",
            "CHIP",
            "CHECKBOX",
            "DATE_PICKER",
            "DRAWER",
            "DROPDOWN",
            "FONTICON",
            "INPUT",
            "LAYOUT",
            "LINK",
            "LIST",
            "MENU",
            "NAVIGATION",
            "PROGRESSBAR",
            "SNACKBAR",
            "TAB",
            "TABS",
            "TOOLTIP"
        ],
        "customProperties": {
            "animation-duration": "0.3s",
            "color-accent": "var(--palette-pink-a200)",
            "color-accent-dark": "var(--palette-pink-700)",
            "color-primary-contrast": "var(--color-dark-contrast)",
            "color-accent-contrast": "var(--color-dark-contrast)"
        },
        "output": "assets/react-toolbox"
    },
```

Any ideas on the cause of the issue?

Many thanks!

**Comment by heckchuckman** [comment]
Update:

It appears that the include array in the package.json file is the culprit. Passing one component type allows the script to run.

It is unclear in the documentation if we need to include each component in the array for the needed styles. Could you clarify?

Thanks again!
